;;; texrs-stdlib.el --- Primitive table for texrs-mode -*- lexical-binding: t; -*-

;; This file is GENERATED by `cargo run --bin gen-emacs-stdlib' from
;; texrs's own primitive corpus (src/corpus.rs).  Do not edit it by hand:
;; `tests/emacs_stdlib.rs' fails when it is not what the generator prints.

;;; Commentary:

;; The names texrs resolves, with the one-line documentation the
;; language server hovers with.  A primitive is here only if the engine
;; dispatches it, so completion cannot offer something that would fail.

;;; Code:

(defconst texrs-primitive-names
  '("\\catcode"
    "^^X"
    "`"
    "\\def"
    "\\gdef"
    "\\edef"
    "\\xdef"
    "\\let"
    "\\futurelet"
    "\\global"
    "\\csname"
    "\\endcsname"
    "\\string"
    "\\the"
    "\\number"
    "\\expandafter"
    "\\noexpand"
    "\\message"
    "\\relax"
    "\\par"
    "\\ignorespaces"
    "\\end"
    "\\ifnum"
    "\\ifodd"
    "\\ifcase"
    "\\iftrue"
    "\\iffalse"
    "\\ifx"
    "\\if"
    "\\ifdefined"
    "\\else"
    "\\or"
    "\\fi"
    "\\ifcat"
    "\\ifdim"
    "\\ifvoid"
    "\\ifhbox"
    "\\ifvbox"
    "\\ifvmode"
    "\\ifhmode"
    "\\ifmmode"
    "\\ifinner"
    "\\ifeof"
    "\\ifcsname"
    "\\count"
    "\\advance"
    "\\multiply"
    "\\divide"
    "\\intercept"
    "\\proceed"
    "\\chardef"
    "\\countdef"
    "\\input"
    "\\rust"
    "\\rustcall"
    "\\rustcompile"
    "\\endrust"
    "{"
    "}"
    "\\begingroup"
    "\\endgroup"
    "\\newcommand"
    "\\renewcommand"
    "\\providecommand"
    "\\DeclareRobustCommand"
    "\\documentclass"
    "\\usepackage"
    "\\RequirePackage"
    "\\PassOptionsToPackage"
    "\\PassOptionsToClass"
    "\\makeatletter"
    "\\makeatother")
  "Every primitive texrs resolves, for completion at point.")

(defconst texrs-stdlib--docs
  (let ((table (make-hash-table :test 'equal)))
    (puthash "\\catcode" "\\catcode  —  Set or read a character's category code. [Category codes]" table)
    (puthash "^^X" "^^X  —  Control-character notation (tex.web §352), in two forms decided by what follows: `^^` and two LOWERCASE hex digits is that hex code, while `^^` and anything else is one character shifted by 64. [Category codes]" table)
    (puthash "`" "`  —  A character code as a number, for a register assignment or a comparison: a backtick followed by a character is that character's code, and the backslash before the character is optional unless it is a control sequence. [Category codes]" table)
    (puthash "\\def" "\\def  —  Define a macro. [Macro definition]" table)
    (puthash "\\gdef" "\\gdef  —  Define globally: the definition survives the enclosing group, where a `\\def` inside braces is undone at the closing brace. [Macro definition]" table)
    (puthash "\\edef" "\\edef  —  Define with the body expanded NOW, so a register read is frozen at definition time and a later assignment cannot move it. [Macro definition]" table)
    (puthash "\\xdef" "\\xdef  —  A global `\\edef`: the body is expanded now and the definition survives the enclosing group. [Macro definition]" table)
    (puthash "\\let" "\\let  —  Give a control sequence another's CURRENT meaning, not a reference to it: redefining the source afterwards does not change the alias. [Macro definition]" table)
    (puthash "\\futurelet" "\\futurelet  —  Look one token past the next without eating either: `\\futurelet\\a\\b\\c` gives `\\a` the meaning of `\\c` and then puts `\\b` and `\\c` back, so the stream is exactly as it was (tex.web §1221). [Macro definition]" table)
    (puthash "\\global" "\\global  —  Prefix making the following assignment global, so it survives the enclosing group. [Macro definition]" table)
    (puthash "\\csname" "\\csname  —  Build a control sequence out of the characters up to `\\endcsname`, so a macro can name another macro. [Expansion]" table)
    (puthash "\\endcsname" "\\endcsname  —  Terminate a `\\csname`. [Expansion]" table)
    (puthash "\\string" "\\string  —  Print a control sequence as text, escape character included — the inverse of `\\csname`. [Expansion]" table)
    (puthash "\\the" "\\the  —  The value of a register, as characters. [Expansion]" table)
    (puthash "\\number" "\\number  —  A scanned number, as characters, with no leading zeros or plus sign. [Expansion]" table)
    (puthash "\\expandafter" "\\expandafter  —  One token of lookahead: hold the next token back, expand what follows it once, then put the held token in front of the result. [Expansion]" table)
    (puthash "\\noexpand" "\\noexpand  —  Suppress expansion of the next token for one step — the token is used for its own sake rather than its meaning. [Expansion]" table)
    (puthash "\\message" "\\message  —  Write to the terminal. [Expansion]" table)
    (puthash "\\relax" "\\relax  —  Do nothing. [Expansion]" table)
    (puthash "\\par" "\\par  —  End a paragraph. [Expansion]" table)
    (puthash "\\ignorespaces" "\\ignorespaces  —  Skip the spaces that follow. [Expansion]" table)
    (puthash "\\end" "\\end  —  Stop the run. [Expansion]" table)
    (puthash "\\ifnum" "\\ifnum  —  Compare two numbers with `<`, `=` or `>`. [Conditionals]" table)
    (puthash "\\ifodd" "\\ifodd  —  True when a number is odd. [Conditionals]" table)
    (puthash "\\ifcase" "\\ifcase  —  Switch on a number: the first case is 0, each `\\or` starts the next, and `\\else` catches everything past the last. [Conditionals]" table)
    (puthash "\\iftrue" "\\iftrue  —  Constant truth. [Conditionals]" table)
    (puthash "\\iffalse" "\\iffalse  —  Constant falsity. [Conditionals]" table)
    (puthash "\\ifx" "\\ifx  —  Compare two meanings: two macros are equal when their parameter texts and bodies match, and two primitives when they are the same primitive. [Conditionals]" table)
    (puthash "\\if" "\\if  —  Compare two character codes after expansion. [Conditionals]" table)
    (puthash "\\ifdefined" "\\ifdefined  —  True when a control sequence has a meaning. [Conditionals]" table)
    (puthash "\\else" "\\else  —  Start the false arm of a conditional. [Conditionals]" table)
    (puthash "\\or" "\\or  —  Start the next case of an `\\ifcase`: the case before the first `\\or` is 0, and each `\\or` moves to the next. [Conditionals]" table)
    (puthash "\\fi" "\\fi  —  End a conditional. [Conditionals]" table)
    (puthash "\\ifcat" "\\ifcat  —  RECOGNISED BUT NOT EVALUATED. [Conditionals]" table)
    (puthash "\\ifdim" "\\ifdim  —  RECOGNISED BUT NOT EVALUATED: there are no dimen registers yet. [Conditionals]" table)
    (puthash "\\ifvoid" "\\ifvoid  —  RECOGNISED BUT NOT EVALUATED: there are no box registers yet. [Conditionals]" table)
    (puthash "\\ifhbox" "\\ifhbox  —  RECOGNISED BUT NOT EVALUATED: there are no box registers yet. [Conditionals]" table)
    (puthash "\\ifvbox" "\\ifvbox  —  RECOGNISED BUT NOT EVALUATED: there are no box registers yet. [Conditionals]" table)
    (puthash "\\ifvmode" "\\ifvmode  —  RECOGNISED BUT NOT EVALUATED: modes belong to the stomach. [Conditionals]" table)
    (puthash "\\ifhmode" "\\ifhmode  —  RECOGNISED BUT NOT EVALUATED: modes belong to the stomach. [Conditionals]" table)
    (puthash "\\ifmmode" "\\ifmmode  —  RECOGNISED BUT NOT EVALUATED: modes belong to the stomach. [Conditionals]" table)
    (puthash "\\ifinner" "\\ifinner  —  RECOGNISED BUT NOT EVALUATED: modes belong to the stomach. [Conditionals]" table)
    (puthash "\\ifeof" "\\ifeof  —  RECOGNISED BUT NOT EVALUATED: there is no file I/O yet. [Conditionals]" table)
    (puthash "\\ifcsname" "\\ifcsname  —  RECOGNISED BUT NOT EVALUATED. [Conditionals]" table)
    (puthash "\\count" "\\count  —  A count register. [Registers]" table)
    (puthash "\\advance" "\\advance  —  Add to a register. [Registers]" table)
    (puthash "\\multiply" "\\multiply  —  Multiply a register. [Registers]" table)
    (puthash "\\divide" "\\divide  —  Divide a register, truncating toward zero as TeX's does. [Registers]" table)
    (puthash "\\intercept" "\\intercept  —  Register advice on macro expansion: `before` puts the handler's body in front of the expansion, `after` puts it behind, and `around` replaces it with `\\proceed` standing for what the macro would have expanded to. [Intercepts]" table)
    (puthash "\\proceed" "\\proceed  —  Inside an `around` handler, what the intercepted macro would have expanded to. [Intercepts]" table)
    (puthash "\\chardef" "\\chardef  —  Define a control sequence that IS a number: `\\chardef\\active=13` makes `\\active` usable wherever a number is scanned, which is how plain.tex writes `\\catcode`\\~=\\active`. [Registers]" table)
    (puthash "\\countdef" "\\countdef  —  Give a count register a name, usable in every position the register itself is: assignment, `\\advance` and `\\the` all reach the same register through either spelling. [Registers]" table)
    (puthash "\\input" "\\input  —  Read another file here, sharing every piece of state with it: a macro it defines is defined afterwards, and a `\\catcode` it sets stays set. [Files]" table)
    (puthash "\\rust" "\\rust  —  Open a block of Rust compiled and loaded at run time. [Inline Rust]" table)
    (puthash "\\rustcall" "\\rustcall  —  Call a function a `\\rust` block exported. [Inline Rust]" table)
    (puthash "\\rustcompile" "\\rustcompile  —  What a `\\rust{ … }` block becomes: compile and register the block whose base64 body follows, up to `\\endrust`. [Inline Rust]" table)
    (puthash "\\endrust" "\\endrust  —  Terminate a `\\rustcompile` body or a `\\rustcall` argument list. [Inline Rust]" table)
    (puthash "{" "{  —  Open a group (category code 1), which scopes the macro table AND the count registers written inside it: the lowered body is wrapped in save/restore for exactly the registers it assigns. [Grouping]" table)
    (puthash "}" "}  —  Close a group (category code 2), undoing every non-global assignment made inside it. [Grouping]" table)
    (puthash "\\begingroup" "\\begingroup  —  Open a group without braces, scoping the macro table and the registers written inside it. [Grouping]" table)
    (puthash "\\endgroup" "\\endgroup  —  Close a `\\begingroup`, undoing every non-global assignment made since it. [Grouping]" table)
    (puthash "\\newcommand" "\\newcommand  —  Define a macro with `n` positional parameters: `\\newcommand{\\x}[2]{#1 and #2}`. [LaTeX]" table)
    (puthash "\\renewcommand" "\\renewcommand  —  Redefine a macro. [LaTeX]" table)
    (puthash "\\providecommand" "\\providecommand  —  Define a macro only if the name is free. [LaTeX]" table)
    (puthash "\\DeclareRobustCommand" "\\DeclareRobustCommand  —  Define a macro. [LaTeX]" table)
    (puthash "\\documentclass" "\\documentclass  —  Consumed, with its optional arguments, and produces nothing. [LaTeX]" table)
    (puthash "\\usepackage" "\\usepackage  —  Consumed with its optional arguments, producing nothing, for the same reason as `\\documentclass`: the package cannot be loaded, and dropping it reads the document minus whatever the package would have drawn. [LaTeX]" table)
    (puthash "\\RequirePackage" "\\RequirePackage  —  Consumed with its optional arguments, producing nothing. [LaTeX]" table)
    (puthash "\\PassOptionsToPackage" "\\PassOptionsToPackage  —  Consumed with both of its arguments, producing nothing, because the package it would have carried options to is never loaded. [LaTeX]" table)
    (puthash "\\PassOptionsToClass" "\\PassOptionsToClass  —  Consumed with both of its arguments, producing nothing. [LaTeX]" table)
    (puthash "\\makeatletter" "\\makeatletter  —  Make `@` a letter (category code 11), so LaTeX's internal names like `\\@ifnextchar` become spellable as single control sequences. [LaTeX]" table)
    (puthash "\\makeatother" "\\makeatother  —  Make `@` an ordinary character again (category code 12), closing a `\\makeatletter` region. [LaTeX]" table)
    table)
  "Primitive name to the line eldoc shows for it.")

(defun texrs-stdlib-signature (name)
  "Return the eldoc line for primitive NAME, or nil."
  (and (stringp name) (gethash name texrs-stdlib--docs)))

(provide 'texrs-stdlib)
;;; texrs-stdlib.el ends here
