;;; texrs-stdlib.el --- Primitive table for texrs-mode -*- lexical-binding: t; -*-

;; This file is GENERATED by `cargo run --bin gen-emacs-stdlib' from
;; texrs's own primitive corpus (src/corpus.rs).  Do not edit it by hand:
;; `tests/emacs_stdlib.rs' fails when it is not what the generator prints.

;;; Commentary:

;; The names texrs resolves, with the one-line documentation the
;; language server hovers with.  A primitive is here only if the engine
;; dispatches it, so completion cannot offer something that would fail.

;;; Code:

(defconst texrs-primitive-names
  '("\\catcode"
    "^^X"
    "`"
    "\\def"
    "\\gdef"
    "\\edef"
    "\\xdef"
    "\\let"
    "\\futurelet"
    "\\global"
    "\\csname"
    "\\endcsname"
    "\\string"
    "\\the"
    "\\number"
    "\\expandafter"
    "\\noexpand"
    "\\message"
    "\\relax"
    "\\par"
    "\\ignorespaces"
    "\\end"
    "\\ifnum"
    "\\ifodd"
    "\\ifcase"
    "\\iftrue"
    "\\iffalse"
    "\\ifx"
    "\\if"
    "\\ifdefined"
    "\\else"
    "\\or"
    "\\fi"
    "\\ifcat"
    "\\ifdim"
    "\\ifvoid"
    "\\ifhbox"
    "\\ifvbox"
    "\\ifvmode"
    "\\ifhmode"
    "\\ifmmode"
    "\\ifinner"
    "\\ifeof"
    "\\ifcsname"
    "\\count"
    "\\advance"
    "\\multiply"
    "\\divide"
    "\\intercept"
    "\\proceed"
    "\\chardef"
    "\\countdef"
    "\\long"
    "\\outer"
    "\\mathcode"
    "\\lccode"
    "\\uccode"
    "\\sfcode"
    "\\delcode"
    "\\mathchardef"
    "\""
    "\\dimen"
    "\\dimendef"
    "\\skip"
    "\\skipdef"
    "\\toks"
    "\\toksdef"
    "\\numexpr"
    "\\dimexpr"
    "\\unless"
    "\\protected"
    "\\detokenize"
    "\\csstring"
    "\\Uchar"
    "\\expanded"
    "\\unexpanded"
    "\\begincsname"
    "\\glueexpr"
    "\\input"
    "\\rust"
    "\\rustcall"
    "\\rustcompile"
    "\\endrust"
    "{"
    "}"
    "\\begingroup"
    "\\endgroup"
    "\\newcommand"
    "\\renewcommand"
    "\\providecommand"
    "\\DeclareRobustCommand"
    "\\documentclass"
    "\\usepackage"
    "\\RequirePackage"
    "\\PassOptionsToPackage"
    "\\PassOptionsToClass"
    "\\begin"
    "\\newpage"
    "\\clearpage"
    "\\cleardoublepage"
    "\\pagebreak"
    "\\chapter"
    "\\section"
    "\\subsection"
    "\\subsubsection"
    "\\tableofcontents"
    "\\setcounter"
    "\\endtitlepage"
    "\\center"
    "\\endcenter"
    "\\centering"
    "\\centerline"
    "\\tabular"
    "\\endtabular"
    "\\longtable"
    "\\endlongtable"
    "\\toprule"
    "\\midrule"
    "\\bottomrule"
    "\\hline"
    "\\tabularnewline"
    "\\endhead"
    "\\endfirsthead"
    "\\endfoot"
    "\\endlastfoot"
    "\\itemize"
    "\\enditemize"
    "\\enumerate"
    "\\endenumerate"
    "\\description"
    "\\enddescription"
    "\\item"
    "\\definecolor"
    "\\providecolor"
    "\\colorlet"
    "\\color"
    "\\textcolor"
    "\\pagecolor"
    "\\setmainfont"
    "\\setromanfont"
    "\\setsansfont"
    "\\setmonofont"
    "\\directlua"
    "\\ttfamily"
    "\\bfseries"
    "\\itshape"
    "\\rmfamily"
    "\\sffamily"
    "\\normalfont"
    "\\makeatletter"
    "\\makeatother")
  "Every primitive texrs resolves, for completion at point.")

(defconst texrs-stdlib--docs
  (let ((table (make-hash-table :test 'equal)))
    (puthash "\\catcode" "\\catcode  —  Set or read a character's category code. [Category codes]" table)
    (puthash "^^X" "^^X  —  Control-character notation (tex.web §352), in two forms decided by what follows: `^^` and two LOWERCASE hex digits is that hex code, while `^^` and anything else is one character shifted by 64. [Category codes]" table)
    (puthash "`" "`  —  A character code as a number, for a register assignment or a comparison: a backtick followed by a character is that character's code, and the backslash before the character is optional unless it is a control sequence. [Category codes]" table)
    (puthash "\\def" "\\def  —  Define a macro. [Macro definition]" table)
    (puthash "\\gdef" "\\gdef  —  Define globally: the definition survives the enclosing group, where a `\\def` inside braces is undone at the closing brace. [Macro definition]" table)
    (puthash "\\edef" "\\edef  —  Define with the body expanded NOW, so a register read is frozen at definition time and a later assignment cannot move it. [Macro definition]" table)
    (puthash "\\xdef" "\\xdef  —  A global `\\edef`: the body is expanded now and the definition survives the enclosing group. [Macro definition]" table)
    (puthash "\\let" "\\let  —  Give a control sequence another's CURRENT meaning, not a reference to it: redefining the source afterwards does not change the alias. [Macro definition]" table)
    (puthash "\\futurelet" "\\futurelet  —  Look one token past the next without eating either: `\\futurelet\\a\\b\\c` gives `\\a` the meaning of `\\c` and then puts `\\b` and `\\c` back, so the stream is exactly as it was (tex.web §1221). [Macro definition]" table)
    (puthash "\\global" "\\global  —  Prefix making the following assignment global, so it survives the enclosing group. [Macro definition]" table)
    (puthash "\\csname" "\\csname  —  Build a control sequence out of the characters up to `\\endcsname`, so a macro can name another macro. [Expansion]" table)
    (puthash "\\endcsname" "\\endcsname  —  Terminate a `\\csname`. [Expansion]" table)
    (puthash "\\string" "\\string  —  Print a control sequence as text, escape character included — the inverse of `\\csname`. [Expansion]" table)
    (puthash "\\the" "\\the  —  The value of a register, as characters. [Expansion]" table)
    (puthash "\\number" "\\number  —  A scanned number, as characters, with no leading zeros or plus sign. [Expansion]" table)
    (puthash "\\expandafter" "\\expandafter  —  One token of lookahead: hold the next token back, expand what follows it once, then put the held token in front of the result. [Expansion]" table)
    (puthash "\\noexpand" "\\noexpand  —  Suppress expansion of the next token for one step — the token is used for its own sake rather than its meaning. [Expansion]" table)
    (puthash "\\message" "\\message  —  Write to the terminal. [Expansion]" table)
    (puthash "\\relax" "\\relax  —  Do nothing. [Expansion]" table)
    (puthash "\\par" "\\par  —  End a paragraph. [Expansion]" table)
    (puthash "\\ignorespaces" "\\ignorespaces  —  Skip the spaces that follow. [Expansion]" table)
    (puthash "\\end" "\\end  —  Stop the run, and ship what it built. [Expansion]" table)
    (puthash "\\ifnum" "\\ifnum  —  Compare two numbers with `<`, `=` or `>`. [Conditionals]" table)
    (puthash "\\ifodd" "\\ifodd  —  True when a number is odd. [Conditionals]" table)
    (puthash "\\ifcase" "\\ifcase  —  Switch on a number: the first case is 0, each `\\or` starts the next, and `\\else` catches everything past the last. [Conditionals]" table)
    (puthash "\\iftrue" "\\iftrue  —  Constant truth. [Conditionals]" table)
    (puthash "\\iffalse" "\\iffalse  —  Constant falsity. [Conditionals]" table)
    (puthash "\\ifx" "\\ifx  —  Compare two meanings: two macros are equal when their parameter texts and bodies match, and two primitives when they are the same primitive. [Conditionals]" table)
    (puthash "\\if" "\\if  —  Compare two character codes after expansion. [Conditionals]" table)
    (puthash "\\ifdefined" "\\ifdefined  —  True when a control sequence has a meaning. [Conditionals]" table)
    (puthash "\\else" "\\else  —  Start the false arm of a conditional. [Conditionals]" table)
    (puthash "\\or" "\\or  —  Start the next case of an `\\ifcase`: the case before the first `\\or` is 0, and each `\\or` moves to the next. [Conditionals]" table)
    (puthash "\\fi" "\\fi  —  End a conditional. [Conditionals]" table)
    (puthash "\\ifcat" "\\ifcat  —  RECOGNISED BUT NOT EVALUATED. [Conditionals]" table)
    (puthash "\\ifdim" "\\ifdim  —  RECOGNISED BUT NOT EVALUATED: there are no dimen registers yet. [Conditionals]" table)
    (puthash "\\ifvoid" "\\ifvoid  —  RECOGNISED BUT NOT EVALUATED: there are no box registers yet. [Conditionals]" table)
    (puthash "\\ifhbox" "\\ifhbox  —  RECOGNISED BUT NOT EVALUATED: there are no box registers yet. [Conditionals]" table)
    (puthash "\\ifvbox" "\\ifvbox  —  RECOGNISED BUT NOT EVALUATED: there are no box registers yet. [Conditionals]" table)
    (puthash "\\ifvmode" "\\ifvmode  —  RECOGNISED BUT NOT EVALUATED: modes belong to the stomach. [Conditionals]" table)
    (puthash "\\ifhmode" "\\ifhmode  —  RECOGNISED BUT NOT EVALUATED: modes belong to the stomach. [Conditionals]" table)
    (puthash "\\ifmmode" "\\ifmmode  —  RECOGNISED BUT NOT EVALUATED: modes belong to the stomach. [Conditionals]" table)
    (puthash "\\ifinner" "\\ifinner  —  RECOGNISED BUT NOT EVALUATED: modes belong to the stomach. [Conditionals]" table)
    (puthash "\\ifeof" "\\ifeof  —  RECOGNISED BUT NOT EVALUATED: there is no file I/O yet. [Conditionals]" table)
    (puthash "\\ifcsname" "\\ifcsname  —  RECOGNISED BUT NOT EVALUATED. [Conditionals]" table)
    (puthash "\\count" "\\count  —  A count register. [Registers]" table)
    (puthash "\\advance" "\\advance  —  Add to a register. [Registers]" table)
    (puthash "\\multiply" "\\multiply  —  Multiply a register. [Registers]" table)
    (puthash "\\divide" "\\divide  —  Divide a register, truncating toward zero as TeX's does. [Registers]" table)
    (puthash "\\intercept" "\\intercept  —  Register advice on macro expansion: `before` puts the handler's body in front of the expansion, `after` puts it behind, and `around` replaces it with `\\proceed` standing for what the macro would have expanded to. [Intercepts]" table)
    (puthash "\\proceed" "\\proceed  —  Inside an `around` handler, what the intercepted macro would have expanded to. [Intercepts]" table)
    (puthash "\\chardef" "\\chardef  —  Define a control sequence that IS a number: `\\chardef\\active=13` makes `\\active` usable wherever a number is scanned, which is how plain.tex writes `\\catcode`\\~=\\active`. [Registers]" table)
    (puthash "\\countdef" "\\countdef  —  Give a count register a name, usable in every position the register itself is: assignment, `\\advance` and `\\the` all reach the same register through either spelling. [Registers]" table)
    (puthash "\\long" "\\long  —  A definition prefix: the macro's arguments may contain `\\par`. [Macro definition]" table)
    (puthash "\\outer" "\\outer  —  A definition prefix: the macro may not then appear in an argument, in a group being scanned as text, or in skipped conditional text. [Macro definition]" table)
    (puthash "\\mathcode" "\\mathcode  —  How a character is set in math mode, as a 15-bit code: class, family and position. [Registers]" table)
    (puthash "\\lccode" "\\lccode  —  A character's lowercase form, which is what `\\lowercase` consults. [Registers]" table)
    (puthash "\\uccode" "\\uccode  —  The same for uppercase, consulted by `\\uppercase`. [Registers]" table)
    (puthash "\\sfcode" "\\sfcode  —  The space factor a character leaves behind, which stretches the space after it. [Registers]" table)
    (puthash "\\delcode" "\\delcode  —  A character's meaning as a delimiter, as a 24-bit code naming a small and a large variant. [Registers]" table)
    (puthash "\\mathchardef" "\\mathchardef  —  Define a control sequence standing for a math code, as `\\chardef` does for a character code. [Registers]" table)
    (puthash "\"" "\"  —  A hexadecimal constant, and `'` an octal one (tex.web \\u{a7}445). [Registers]" table)
    (puthash "\\dimen" "\\dimen  —  A dimension register. [Registers]" table)
    (puthash "\\dimendef" "\\dimendef  —  Give a dimension register a name, as `\\countdef` does for a count. [Registers]" table)
    (puthash "\\skip" "\\skip  —  A glue register: a natural dimension that can stretch and shrink. [Registers]" table)
    (puthash "\\skipdef" "\\skipdef  —  Give a glue register a name, as `\\countdef` and `\\dimendef` do for theirs. [Registers]" table)
    (puthash "\\toks" "\\toks  —  A token register: a token list stored VERBATIM, since nothing inside the braces expands -- which is the difference between it and a macro, and why `\\toks0={\\x}` reads back as `\\x` whatever `\\x` means. [Registers]" table)
    (puthash "\\toksdef" "\\toksdef  —  Give a token register a name, as `\\countdef` does for a count. [Registers]" table)
    (puthash "\\numexpr" "\\numexpr  —  An integer expression, closed by an optional `\\relax`: `+`, `-`, `*`, `/` with ordinary precedence and parentheses. [Registers]" table)
    (puthash "\\dimexpr" "\\dimexpr  —  The same for dimensions: the operands are lengths and the multiplier and divisor are integers, so `\\dimexpr 1pt*3` is three points. [Registers]" table)
    (puthash "\\unless" "\\unless  —  Negate the conditional that follows: `\\unless\\ifnum 1>2 A\\else B\\fi` runs A. [Conditionals]" table)
    (puthash "\\protected" "\\protected  —  A definition prefix: the macro does not expand inside an `\\edef`, it survives as itself and runs when the result does. [Macro definition]" table)
    (puthash "\\detokenize" "\\detokenize  —  The tokens of `{...}` written as text, by the token-list rule: a control word carries a trailing space, a one-character control sequence does not. [Expansion]" table)
    (puthash "\\csstring" "\\csstring  —  `\\string` without the escape character: `\\csstring\\foo` is `foo` where `\\string\\foo` is `\\foo`. [Expansion]" table)
    (puthash "\\Uchar" "\\Uchar  —  The character with the given code: `\\Uchar65` is `A`. [Expansion]" table)
    (puthash "\\expanded" "\\expanded  —  Expand the group's contents completely, here and now, and put the result back. [Expansion]" table)
    (puthash "\\unexpanded" "\\unexpanded  —  The opposite: the group's tokens are used as they stand. [Expansion]" table)
    (puthash "\\begincsname" "\\begincsname  —  `\\csname` that does not define what it does not find: an unknown name expands to nothing, where `\\csname` would make it `\\relax` and leave it defined ever after. [Expansion]" table)
    (puthash "\\glueexpr" "\\glueexpr  —  A glue expression, the same grammar as `\\numexpr` over glue. [Registers]" table)
    (puthash "\\input" "\\input  —  Read another file here, sharing every piece of state with it: a macro it defines is defined afterwards, and a `\\catcode` it sets stays set. [Files]" table)
    (puthash "\\rust" "\\rust  —  Open a block of Rust compiled and loaded at run time. [Inline Rust]" table)
    (puthash "\\rustcall" "\\rustcall  —  Call a function a `\\rust` block exported. [Inline Rust]" table)
    (puthash "\\rustcompile" "\\rustcompile  —  What a `\\rust{ … }` block becomes: compile and register the block whose base64 body follows, up to `\\endrust`. [Inline Rust]" table)
    (puthash "\\endrust" "\\endrust  —  Terminate a `\\rustcompile` body or a `\\rustcall` argument list. [Inline Rust]" table)
    (puthash "{" "{  —  Open a group (category code 1), which scopes the macro table AND the count registers written inside it: the lowered body is wrapped in save/restore for exactly the registers it assigns. [Grouping]" table)
    (puthash "}" "}  —  Close a group (category code 2), undoing every non-global assignment made inside it. [Grouping]" table)
    (puthash "\\begingroup" "\\begingroup  —  Open a group without braces, scoping the macro table and the registers written inside it. [Grouping]" table)
    (puthash "\\endgroup" "\\endgroup  —  Close a `\\begingroup`, undoing every non-global assignment made since it. [Grouping]" table)
    (puthash "\\newcommand" "\\newcommand  —  Define a macro with `n` positional parameters: `\\newcommand{\\x}[2]{#1 and #2}`. [LaTeX]" table)
    (puthash "\\renewcommand" "\\renewcommand  —  Redefine a macro. [LaTeX]" table)
    (puthash "\\providecommand" "\\providecommand  —  Define a macro only if the name is free. [LaTeX]" table)
    (puthash "\\DeclareRobustCommand" "\\DeclareRobustCommand  —  Define a macro. [LaTeX]" table)
    (puthash "\\documentclass" "\\documentclass  —  Consumed, with its arguments, and produces nothing except the page. [LaTeX]" table)
    (puthash "\\usepackage" "\\usepackage  —  Consumed with its arguments, producing nothing, for the same reason as `\\documentclass`: the package cannot be loaded, and dropping it reads the document minus whatever the package would have drawn. [LaTeX]" table)
    (puthash "\\RequirePackage" "\\RequirePackage  —  Consumed with its optional arguments, producing nothing. [LaTeX]" table)
    (puthash "\\PassOptionsToPackage" "\\PassOptionsToPackage  —  Consumed with both of its arguments, producing nothing, because the package it would have carried options to is never loaded. [LaTeX]" table)
    (puthash "\\PassOptionsToClass" "\\PassOptionsToClass  —  Consumed with both of its arguments, producing nothing. [LaTeX]" table)
    (puthash "\\begin" "\\begin  —  Open an environment. [LaTeX]" table)
    (puthash "\\newpage" "\\newpage  —  Start a new page. [LaTeX]" table)
    (puthash "\\clearpage" "\\clearpage  —  Start a new page, after placing any pending floats. [LaTeX]" table)
    (puthash "\\cleardoublepage" "\\cleardoublepage  —  Start a new page, and in a two-sided document a new RIGHT-hand one. [LaTeX]" table)
    (puthash "\\pagebreak" "\\pagebreak  —  Break the page. [LaTeX]" table)
    (puthash "\\chapter" "\\chapter  —  Begin a chapter, on a new page. [LaTeX]" table)
    (puthash "\\section" "\\section  —  Begin a section: the heading text, with a line of vertical space above it and a line below. [LaTeX]" table)
    (puthash "\\subsection" "\\subsection  —  Begin a subsection. [LaTeX]" table)
    (puthash "\\subsubsection" "\\subsubsection  —  Begin a subsubsection, set as `\\section` and `\\subsection` are: its own lines, with a line of vertical space above and below. [LaTeX]" table)
    (puthash "\\tableofcontents" "\\tableofcontents  —  Set a table of contents: one line per heading, with leader dots and the page it starts on. [LaTeX]" table)
    (puthash "\\setcounter" "\\setcounter  —  Set a counter. [LaTeX]" table)
    (puthash "\\endtitlepage" "\\endtitlepage  —  End a title page, which `\\end{titlepage}` runs. [LaTeX]" table)
    (puthash "\\center" "\\center  —  Start centring the lines that follow. [LaTeX]" table)
    (puthash "\\endcenter" "\\endcenter  —  Stop centring: what `\\end{center}` runs, and the close of the region `\\center` opened. [LaTeX]" table)
    (puthash "\\centering" "\\centering  —  Centre every line up to the end of the group or the environment that holds it. [LaTeX]" table)
    (puthash "\\centerline" "\\centerline  —  Centre exactly its argument, on a line of its own. [LaTeX]" table)
    (puthash "\\tabular" "\\tabular  —  Open a table. [LaTeX]" table)
    (puthash "\\endtabular" "\\endtabular  —  Close a table: what `\\end{tabular}` runs. [LaTeX]" table)
    (puthash "\\longtable" "\\longtable  —  Open a longtable, which is set exactly as `tabular` is. [LaTeX]" table)
    (puthash "\\endlongtable" "\\endlongtable  —  Close a longtable: what `\\end{longtable}` runs, and the same close `\\endtabular` is. [LaTeX]" table)
    (puthash "\\toprule" "\\toprule  —  booktabs' rule above a table, drawn as a filled rectangle the width of the table at booktabs' own `\\heavyrulewidth` of 0.08em. [LaTeX]" table)
    (puthash "\\midrule" "\\midrule  —  booktabs' rule between a table's head and its body, drawn at `\\lightrulewidth` -- 0.05em, thinner than the two outer rules, which is the whole visual difference between them. [LaTeX]" table)
    (puthash "\\bottomrule" "\\bottomrule  —  booktabs' rule under a table, drawn at `\\heavyrulewidth` as `\\toprule` is. [LaTeX]" table)
    (puthash "\\hline" "\\hline  —  The kernel's own horizontal rule across a table, drawn the way `\\midrule` is. [LaTeX]" table)
    (puthash "\\tabularnewline" "\\tabularnewline  —  End a table row. [LaTeX]" table)
    (puthash "\\endhead" "\\endhead  —  End longtable's head: everything above it is set at the top of EVERY page the table runs onto, not only the first. [LaTeX]" table)
    (puthash "\\endfirsthead" "\\endfirsthead  —  End longtable's FIRST head, when it differs from the one that repeats. [LaTeX]" table)
    (puthash "\\endfoot" "\\endfoot  —  End longtable's foot: what stands at the bottom of every page the table runs PAST -- so on no page at all when it fits on one, and never on the last, where `\\endlastfoot` stands instead. [LaTeX]" table)
    (puthash "\\endlastfoot" "\\endlastfoot  —  End longtable's LAST foot: what is set once, under the end of the table, where `\\endfoot` stands under every page before it. [LaTeX]" table)
    (puthash "\\itemize" "\\itemize  —  Open a bulleted list. [LaTeX]" table)
    (puthash "\\enditemize" "\\enditemize  —  Close a bulleted list: what `\\end{itemize}` runs. [LaTeX]" table)
    (puthash "\\enumerate" "\\enumerate  —  Open a numbered list, set exactly as `itemize` is except for the mark: each item carries its own number in the list, counted from one. [LaTeX]" table)
    (puthash "\\endenumerate" "\\endenumerate  —  Close a numbered list: what `\\end{enumerate}` runs, and the same close `\\enditemize` is. [LaTeX]" table)
    (puthash "\\description" "\\description  —  Open a list of terms. [LaTeX]" table)
    (puthash "\\enddescription" "\\enddescription  —  Close a list of terms: what `\\end{description}` runs, and the same close the other two lists have. [LaTeX]" table)
    (puthash "\\item" "\\item  —  Start a list item: its own line, at the depth of the list holding it, with the mark that list sets -- a bullet, a number, or a bold term. [LaTeX]" table)
    (puthash "\\definecolor" "\\definecolor  —  Name a colour: `\\definecolor{neonCyan}{HTML}{05D9E8}`. [LaTeX]" table)
    (puthash "\\providecolor" "\\providecolor  —  Define a colour only if that name is not already defined. [LaTeX]" table)
    (puthash "\\colorlet" "\\colorlet  —  Give an existing colour another name. [LaTeX]" table)
    (puthash "\\color" "\\color  —  Switch the colour of everything that follows, until the group holding it closes -- a switch rather than a wrapper, which is why `{\\color{red}...}` colours only what is inside the braces. [LaTeX]" table)
    (puthash "\\textcolor" "\\textcolor  —  Colour exactly one argument: `\\textcolor{neonCyan}{words}`. [LaTeX]" table)
    (puthash "\\pagecolor" "\\pagecolor  —  Paint the page. [LaTeX]" table)
    (puthash "\\setmainfont" "\\setmainfont  —  Record the document's body typeface, and keep the name rather than dropping it. [LaTeX]" table)
    (puthash "\\setromanfont" "\\setromanfont  —  The older fontspec spelling of `\\setmainfont`, and the same thing here: it fills the same slot, so whichever of the two the preamble writes last is the family the PDF backend embeds or maps. [LaTeX]" table)
    (puthash "\\setsansfont" "\\setsansfont  —  Record the document's sans-serif family. [LaTeX]" table)
    (puthash "\\setmonofont" "\\setmonofont  —  Record the document's monospace family, the counterpart of `\\setsansfont`, and the face `\\ttfamily` selects. [LaTeX]" table)
    (puthash "\\directlua" "\\directlua  —  Hand a chunk to LuaTeX's embedded Lua interpreter. [LaTeX]" table)
    (puthash "\\ttfamily" "\\ttfamily  —  Set in the monospace face, until the group holding the declaration closes. [LaTeX]" table)
    (puthash "\\bfseries" "\\bfseries  —  Set in the bold face, until the group holding the declaration closes; `\\textbf{...}` is `{\\bfseries ...}`. [LaTeX]" table)
    (puthash "\\itshape" "\\itshape  —  Set in the italic face, until the group holding the declaration closes; `\\textit{...}` and `\\emph{...}` are both `{\\itshape ...}`. [LaTeX]" table)
    (puthash "\\rmfamily" "\\rmfamily  —  Back to the body face, until the group holding the declaration closes. [LaTeX]" table)
    (puthash "\\sffamily" "\\sffamily  —  Select the sans-serif family. [LaTeX]" table)
    (puthash "\\normalfont" "\\normalfont  —  Undo every face declaration in force and set in the body face, to the end of the group. [LaTeX]" table)
    (puthash "\\makeatletter" "\\makeatletter  —  Make `@` a letter (category code 11), so LaTeX's internal names like `\\@ifnextchar` become spellable as single control sequences. [LaTeX]" table)
    (puthash "\\makeatother" "\\makeatother  —  Make `@` an ordinary character again (category code 12), closing a `\\makeatletter` region. [LaTeX]" table)
    table)
  "Primitive name to the line eldoc shows for it.")

(defun texrs-stdlib-signature (name)
  "Return the eldoc line for primitive NAME, or nil."
  (and (stringp name) (gethash name texrs-stdlib--docs)))

(provide 'texrs-stdlib)
;;; texrs-stdlib.el ends here
